In [6]:
import pandas as pd
import numpy as np

### Array 

--Arraylar içerisinde tek tipte veri tutar. Yani float ise hepsi float, tam sayı ise hepsi tam sayı olmalı.

--Örneğin 5 tane tam sayı 4 tane float olsun. Bunu değiştirmek istediğimde en kapsayıcı veri tipi ne ise ona göre değiştiriyor.

In [7]:
data1 = [6,7.5,8,0,1]

In [8]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
arr1.dtype

dtype('float64')

In [11]:
data2 = [[1,2,3], [4,3,2]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3],
       [4, 3, 2]])

In [14]:
arr2.dtype

dtype('int64')

In [17]:
np.zeros(10) ## 10 tane sıfırdan oluşan array oluştur demek.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((4,4)) ## 4x4'lük 0 dan oluşan bir array oluştur.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.full((4,5),10) #4x5'lik bir matrix oluştur ve 10'la doldur.

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [21]:
arr1 = np.array([1,2,3], dtype=float)

In [22]:
arr1 = np.array([1,2,3], dtype=int)

In [23]:
arr1.dtype

dtype('int64')

In [24]:
arr2.dtype

dtype('int64')

In [25]:
arr = np.array([1,2,3,4,5,6])

In [26]:
arr.dtype

dtype('int64')

In [28]:
arr = arr.astype(float)

In [29]:
arr.dtype

dtype('float64')

In [30]:
arr = np.arange(5,10)

In [31]:
x = np.array([[1,2,3], [4,5,6]])

In [ ]:
x.shape ## matrix sayısı

(2, 3)

In [34]:
x.ndim ## kaç boyutlu olduğu

2

In [35]:
a = np.array([[1,2,3], [4,5,6]])

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.append(a,[[4,6,8]], axis = 0) ## axis satır olarak mı ekleyim sütun olarak mı sorusu

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 8]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.append(a,[[4], [8]], axis=1) # sütuna 4 ve 8 ekledik

array([[1, 2, 3, 4],
       [4, 5, 6, 8]])

In [48]:
k = [2,4,4]

In [49]:
k[0]

2

In [50]:
k = [[2,3,4]]

In [55]:
k[0][1] ## iç içe liste olduğundan 2 index yazdık. boyut bunlar aslında

3

In [56]:
array = np.array([2,4,4])

In [57]:
array.shape

(3,)

In [58]:
array.ndim

1

In [59]:
array = np.array([[2,4,4]])

In [62]:
array.shape ## 1 satırım var, 3 tane sütunum var

(1, 3)

In [63]:
array.ndim ## 2 boyutlu bir array

2

## Operations between Arrays and Scalars

-- Numpy'da for loop kullanılmaz, direkt olarak kendisi array içinde uygulayabiliyor.

-- Temel pythonda bir liste içindeki veriyle sayıyı çarpmak için for loop uygulanması gerekiyor. Numpy'da böyle değil, bu hız farkını ortaya çıkartıyor.

-- İki tane array verdiğinde ve işlem yapmak istediğinde, 2 arrayda aynı indexteki değerleri topluyor.

In [72]:
a = np.arange(10);a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a*5 ## bir işlem yapılıyorsa tüm arraye uygulanıyor.

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [73]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
b = np.arange(10)

In [75]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a+b # vektörel işlemler

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


Aşağıdaki örnekte aynı örneğin temel python ve numpydaki uygulamaları var.

Görüldüğü gibi bir listeyi veya arrayi 5 ile çarpmak istediğimizi düşünelim,
Birinde for loop ile listedeki tüm değerler üzerinde gezinerek 5 ile çarpmak zorundayken, diğerinde array içerisinde olduğundan direkt olarak k*5 yaparak tüm değerleri 5 ile çarpabiliyoruz.

Bu durum büyük datasetlerde hem zamandan tasarruf hem de kolaylık sağlıyor.

In [78]:
k = [1,10,20]

In [84]:
for i in k:
    x = i*5
    print(x)

5
50
100

In [86]:
k_array = np.array(k)

In [87]:
k_array*5

array([  5,  50, 100])

In [88]:
my_list = [[1,2,3], [4,5,6], [7,8,9]]

In [91]:
new_array = np.array(my_list)

In [92]:
new_array*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [93]:
np.array(my_list)*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

### Ndarray indexing with slices

-- Satırı söylemek gerekir, sütunları belirtmesen de olur. 

-- Satır default olarak seçili geliyor.

In [95]:
a = np.arange(5,11)

In [98]:
a

array([ 5,  6,  7,  8,  9, 10])

In [96]:
a[0]

np.int64(5)

In [97]:
a[-1]

np.int64(10)

In [100]:
a[0:3] # 2. indexte kadar getirir.

array([5, 6, 7])

In [101]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [109]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
arr2d.ndim

2

In [105]:
arr2d[1,1] ## ilki satır ikinicsi sütun

np.int64(5)

In [112]:
arr2d[1:,1]

array([5, 8])

In [110]:
arr2d[1:,1:2]

array([[5],
       [8]])

In [113]:
arr2d[1:,1:2].shape

(2, 1)

In [115]:
arr2d[1:,1].shape

(2,)

In [116]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [121]:
arr2d[:2] ## tek slice yazıldığında sadece satırı kabul eder default olarak bütün sütunları alır

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
arr2d[:,1:] # ilk olarak bütün satırları seçtik, kolon olarak 1'den sona kadar

array([[2, 3],
       [5, 6],
       [8, 9]])

In [126]:
a = np.arange(12).reshape(2,3,2) ## reshape --> yeniden şekillendirme, 3 boyutlu veri yaptık

In [125]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [127]:
a[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

### 3 Boyutlu Matrix

axis = 0 --> eksen
axis = 1 --> satır
axis = 2 --> sütun

-- Yani önce 3 boyutlu düşün matris seçiliyor.

In [129]:
a[1,2] ## Yani birinci matrisin, 2. satırı gelmiş oldu

array([10, 11])

In [131]:
a[1,2,0] ## Birinci eksenin, 2.satırının 0. indexi geldi.

np.int64(10)

In [133]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

3,5,9 ve 11i getir

In [142]:
a[:,1:,1]

array([[ 3,  5],
       [ 9, 11]])

In [143]:
a = np.arange(24).reshape(2,2,3,2)

In [144]:
a

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [145]:
a[1]

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [149]:
a[1,0,2,1] ## 1.küpün, 0. matrisinin, 2.satırının, 1.indexi

np.int64(17)

In [152]:
arr = np.arange(10)

In [154]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
arr_slicer = arr[5:8] # 5,6,7

arr_slicer tarafında veriyi kopyalamadık, buna view deniyor. dolayısıyla 6 sayısını 1000e çevirirken hem ana array de hem de sonradan belirlediğim arrayde sayı değişmiiş oldu

In [156]:
arr_slicer

array([5, 6, 7])

In [158]:
arr_slicer[1] = 1000

In [159]:
arr_slicer

array([   5, 1000,    7])

In [160]:
arr

array([   0,    1,    2,    3,    4,    5, 1000,    7,    8,    9])

In [161]:
arr_slicer[:] = 64

In [162]:
arr_slicer

array([64, 64, 64])

In [163]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### View'ün mantığı nedir?

-- Pandasta DF'ler var, tablo yani. Kolon seçip toplamını alacağımızı düşünelim, kolon seçildiği zaman veriyi kopyalaması gereksiz mevcut kolondan toplayabilir.

-- Bu sebeple kolonu kopyalamaması mantıklı big data tarafı için. 

-- Kısaca slice alındığı zaman veriyi kopyalamaz.

In [166]:
arr[5:8] = -1

In [167]:
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [168]:
arr_slicer

array([-1, -1, -1])

-- Hem normal array hem de arr_slicer'da uygulandı. View'dan dolayı. Yani tek bir veri var iki değişkenle yönetilebiliyor. <p>
-- Pandasta da aynı durum geçerli, veri kopyalanmıyor her ikisinde de değiştiriyor.

In [170]:
import pandas as pd

In [171]:
df = pd.DataFrame({"foo": [1,2,3], "bar": [4,5,6]})

In [172]:
df

   foo  bar
0    1    4
1    2    5
2    3    6

In [173]:
subset = df["foo"]

In [174]:
subset

0    1
1    2
2    3
Name: foo, dtype: int64

In [175]:
subset.iloc[0] = 100

In [176]:
subset

0    100
1      2
2      3
Name: foo, dtype: int64

In [177]:
df

   foo  bar
0  100    4
1    2    5
2    3    6

In [178]:
df["foo"].iloc[0] = 101

In [179]:
df

   foo  bar
0  101    4
1    2    5
2    3    6

In [180]:
pd.__version__

'2.3.3'

### Copy Kullanımı

--Aşağıdaki örnekte görüldüğü gibi, copy denerek aslında array bilgisayara kopyalanır. <p>
--a_sub ile kopyalanmış veride 0.satırdaki 0.sütununu 100 yapıyoruz. <p>
--a_sub 0,0 100 olurken a arrayindeki 0,0 değerini değiştirmemiş oldu. <p>

-- Numpy'da slice alındığı zaman kendisi otomatik kopyalamaz, avantajı büyük bir veri var ise kopyalamadan işlem yapılabilir. <p>

-- Pandasta da kopyalamama eğilimi var, inplace parametresi ile orijinalde değişiklik de yapılabiliyor.

In [181]:
a = np.arange(20).reshape(4,5)

In [182]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [185]:
a[:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [186]:
a_sub = a[:2,2:].copy()

In [187]:
a_sub[0,0] = 100

In [188]:
a_sub

array([[100,   3,   4],
       [  7,   8,   9]])

In [189]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])