In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
pd.__version__

'2.3.3'

### Series

--Tek boyutlu array'e benzer. Array'den tek farkı, index var. <p>
--Tek tip veri tutulması gerekir <p>

In [3]:
obj = pd.Series([4,7,-5,3], index = ["d", "b", "a", "c"])

In [4]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
type(obj.values)

numpy.ndarray

In [7]:
obj.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
type(obj.index)

pandas.core.indexes.base.Index

In [9]:
obj['a']

np.int64(-5)

In [10]:
obj[["d", "b", "c"]]

d    4
b    7
c    3
dtype: int64

In [13]:
obj > 0 ## boolean

d     True
b     True
a    False
c     True
dtype: bool

In [14]:
obj[obj > 0] ## boolean indexleme

d    4
b    7
c    3
dtype: int64

In [15]:
obj*2

d     8
b    14
a   -10
c     6
dtype: int64

In [18]:
'b' in obj ## veri yapısı içinde b var mı? Indexlerde arama yapıyor.

True

In [20]:
4 in obj ## indexte baktığından dolayı false getirdi

False

In [24]:
obj == 4

d     True
b    False
a    False
c    False
dtype: bool

In [25]:
(obj == 4).sum()

np.int64(1)

In [26]:
4 in obj.values

True

In [27]:
sdata = {"Ohio": 35000, "Texas": 71000, "Gregon": 16000, "Utah": 5000}

In [28]:
obj3 = pd.Series(sdata)

In [29]:
obj3

Ohio      35000
Texas     71000
Gregon    16000
Utah       5000
dtype: int64

In [30]:
type(obj3)

pandas.core.series.Series

In [34]:
states = ["California", "Ohio", "Gregon", "Texas"]

In [35]:
ob4 = pd.Series(sdata, index=states)

In [36]:
ob4

California        NaN
Ohio          35000.0
Gregon        16000.0
Texas         71000.0
dtype: float64

In [38]:
pd.isnull(ob4)

California     True
Ohio          False
Gregon        False
Texas         False
dtype: bool

In [39]:
pd.notnull(ob4)

California    False
Ohio           True
Gregon         True
Texas          True
dtype: bool

In [41]:
ob4.isnull() ### metod olarak da değiştirilebiliyor

California     True
Ohio          False
Gregon        False
Texas         False
dtype: bool

In [42]:
ob4.name = "population"

In [43]:
ob4

California        NaN
Ohio          35000.0
Gregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [44]:
ob4.index.name = 'state'

In [45]:
ob4

state
California        NaN
Ohio          35000.0
Gregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## Dataframe

In [47]:
df = pd.DataFrame([[1,2,3], [4,5,6]])

In [48]:
df

   0  1  2
0  1  2  3
1  4  5  6

In [49]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
            'year': [2000, 2001, 2002, 2001, 2002, 2003],
            'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [50]:
frame = pd.DataFrame(data);frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [51]:
frame["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [52]:
frame.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [58]:
frame[["year","pop"]]

   year  pop
0  2000  1.5
1  2001  1.7
2  2002  3.6
3  2001  2.4
4  2002  2.9
5  2003  3.2

In [ ]:
frame.year

<bound method Series.pop of 0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64>

In [62]:
frame.pop ## dataframein pop diye bir fonksiyon isimi var, o yüzden olmadı

<bound method DataFrame.pop of     state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2>

In [64]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [66]:
frame['debt'] = 16.5

In [67]:
frame

    state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [68]:
frame["debt"] = np.arange(10,16)

In [69]:
frame

    state  year  pop  debt
0    Ohio  2000  1.5    10
1    Ohio  2001  1.7    11
2    Ohio  2002  3.6    12
3  Nevada  2001  2.4    13
4  Nevada  2002  2.9    14
5  Nevada  2003  3.2    15

In [71]:
val = pd.Series([-1.2, -1.5, -1.7], index = [2,4,5])

In [73]:
frame["debt"] = val

In [75]:
frame # seriesde index olduğundan eşleştirdi

    state  year  pop  debt
0    Ohio  2000  1.5   NaN
1    Ohio  2001  1.7   NaN
2    Ohio  2002  3.6  -1.2
3  Nevada  2001  2.4   NaN
4  Nevada  2002  2.9  -1.5
5  Nevada  2003  3.2  -1.7

In [76]:
del frame["debt"]

In [77]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [78]:
frame["size"] = np.arange(100,700,100)

In [79]:
frame

    state  year  pop  size
0    Ohio  2000  1.5   100
1    Ohio  2001  1.7   200
2    Ohio  2002  3.6   300
3  Nevada  2001  2.4   400
4  Nevada  2002  2.9   500
5  Nevada  2003  3.2   600

In [80]:
frame.columns

Index(['state', 'year', 'pop', 'size'], dtype='object')

In [81]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [82]:
frame.values

array([['Ohio', 2000, 1.5, 100],
       ['Ohio', 2001, 1.7, 200],
       ['Ohio', 2002, 3.6, 300],
       ['Nevada', 2001, 2.4, 400],
       ['Nevada', 2002, 2.9, 500],
       ['Nevada', 2003, 3.2, 600]], dtype=object)

In [83]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c']);obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [87]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
#reindex eksik olan indexleri de dolduruyor

In [86]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [88]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                             index=['a', 'c', 'd'],
                            columns=['Ohio', 'Texas', 'California'])

In [92]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [90]:
frame2 = frame.reindex(['a', 'b', 'c', 'd']); frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [91]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [93]:
states = ["Texas", "Utah", "California"]

In [95]:
frame.reindex(columns = states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [96]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [97]:
## drop

In [98]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e']);obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [99]:
 new_obj = obj.drop('c') ; new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [100]:
 data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                           index=['Ohio', 'Colorado', 'Utah', 'New York'],
                           columns=['one', 'two', 'three', 'four'])

In [101]:
data.drop("two", axis = 1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [103]:
data.drop(["one", "four"], axis = 1)

          two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [105]:
data.drop(["two", "three"], axis = 'columns', inplace=True)

In [106]:
data

          one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

## Indexing, Selection, and Filtering

In [107]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                           index=['Ohio', 'Colorado', 'Utah', 'New York'],
                           columns=['one', 'two', 'three', 'four'])

In [108]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [109]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

## boolean indexing

In [113]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## booelan indexing

In [114]:
data["three"] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [115]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

-- iloc: index location. sıra kullanacaksak bu kullanılır <p>

-- loc: değere göre çalışılacaksa loc

In [131]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [118]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [119]:
data.loc[["Colorado", "Utah"]]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [120]:
data.loc[:, ["two", "four"]]

          two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [123]:
data.loc[["Ohio", "Utah"]]

      one  two  three  four
Ohio    0    1      2     3
Utah    8    9     10    11

In [125]:
data.loc[:,["one", "three"]]

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [127]:
data.loc[["Ohio", "Utah"],["one", "three"]]

      one  three
Ohio    0      2
Utah    8     10

In [128]:
data.iloc[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [152]:
data.iloc[:, -2:] # tüm satılar son 2 kolon

          three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [155]:
data.iloc[:2, -2:] # ilk 2 satır son 2 kolon

          three  four
Ohio          2     3
Colorado      6     7

## Function Application and Mapping

In [157]:
frame = pd.DataFrame(np.random.randint(0,10,(4, 3)), columns=list('bde'),
                         index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [158]:
frame

        b  d  e
Utah    8  9  0
Ohio    7  0  4
Texas   1  5  8
Oregon  6  9  0

In [162]:
data = pd.read_csv('/Users/fesavaskurt/Python&ML/Kodlarım/Python/ITU/Veri_Analizi_ve_Keşifci_veri_Analizi/pandas_norway_carsales/norway_new_car_sales_by_model.csv', encoding="latin-1")

In [163]:
data.head()

   Year  Month         Make              Model  Quantity   Pct
0  2007      1  Volkswagen   Volkswagen Passat      1267  10.0
1  2007      1      Toyota         Toyota Rav4       819   6.5
2  2007      1      Toyota      Toyota Avensis       787   6.2
3  2007      1  Volkswagen     Volkswagen Golf       720   5.7
4  2007      1      Toyota      Toyota Corolla       691   5.4

In [166]:
data[["Quantity"]]

      Quantity
0         1267
1          819
2          787
3          720
4          691
...        ...
2689       216
2690       214
2691       205
2692       202
2693       202

[2694 rows x 1 columns]

In [186]:
data[(data["Quantity"] > 500) & (data["Make"] == "Toyota ")]

      Year  Month     Make           Model  Quantity       Pct
1     2007      1  Toyota      Toyota Rav4       819  6.500000
2     2007      1  Toyota   Toyota Avensis       787  6.200000
4     2007      1  Toyota   Toyota Corolla       691  5.400000
21    2007      2  Toyota   Toyota Avensis       540  5.500000
22    2007      2  Toyota   Toyota Corolla       505  5.200000
41    2007      3  Toyota   Toyota Avensis       521  4.600000
121   2007      7  Toyota   Toyota Avensis       587  4.900000
182   2007     10  Toyota   Toyota Avensis       535  4.600000
202   2007     11  Toyota   Toyota Avensis       502  4.800000
641   2009      9  Toyota     Toyota Prius       515  5.400000
1659  2013      9  Toyota     Toyota Auris       511  4.200000
1689  2013     10  Toyota     Toyota Auris       679  5.300000
1709  2013     11  Toyota     Toyota Auris       525  4.300000
1779  2014      1  Toyota     Toyota Auris       563  4.900000
1939  2014      9  Toyota     Toyota Auris       537  4.600000
2020  2015      1  Toyota      Toyota Rav4       535  5.100000
2098  2015      4  Toyota     Toyota Auris       509  3.982162
2218  2015      9  Toyota     Toyota Auris       535  4.300000
2238  2015     10  Toyota     Toyota Auris       574  4.300000
2400  2016      3  Toyota     Toyota Auris       507  3.654054
2574  2016      8  Toyota      Toyota Rav4       735  5.600000
2594  2016      9  Toyota      Toyota Rav4       581  4.200000
2635  2016     11  Toyota      Toyota Rav4       513  3.900000

In [191]:
data[(data["Quantity"] > 500) & (data["Make"] == "Toyota ") & (data["Model"] == "Toyota Rav4")]

      Year  Month     Make        Model  Quantity  Pct
1     2007      1  Toyota   Toyota Rav4       819  6.5
2020  2015      1  Toyota   Toyota Rav4       535  5.1
2574  2016      8  Toyota   Toyota Rav4       735  5.6
2594  2016      9  Toyota   Toyota Rav4       581  4.2
2635  2016     11  Toyota   Toyota Rav4       513  3.9

In [194]:
data.query("Quantity > 500 & Make == 'Toyota' & Model == 'Toyota Rav4'")

Empty DataFrame
Columns: [Year, Month, Make, Model, Quantity, Pct]
Index: []

In [195]:
data.query("2010 < Year < 20215 & Make == 'Toyota '")

      Year  Month     Make           Model  Quantity  Pct
962   2011      1  Toyota   Toyota Avensis       414  4.0
963   2011      1  Toyota     Toyota Auris       409  3.9
973   2011      1  Toyota      Toyota Rav4       194  1.9
975   2011      1  Toyota     Toyota Prius       173  1.7
983   2011      2  Toyota   Toyota Avensis       326  3.1
...    ...    ...      ...             ...       ...  ...
2671  2016     12  Toyota     Toyota Prius       104  0.8
2676  2017      1  Toyota      Toyota Rav4       473  3.6
2680  2017      1  Toyota     Toyota Yaris       343  2.6
2682  2017      1  Toyota     Toyota Auris       280  2.1
2684  2017      1  Toyota      Toyota C-HR       246  1.9

[273 rows x 6 columns]

In [196]:
data.query("2010 < Year < 20215 & Make == 'Toyota '").sum()

Year                                                   549718
Month                                                    1717
Make        Toyota Toyota Toyota Toyota Toyota Toyota Toyo...
Model       Toyota AvensisToyota AurisToyota Rav4Toyota Pr...
Quantity                                                80974
Pct                                                669.308215
dtype: object

In [197]:
data.query("2010 < Year < 20215 & Make == 'Toyota '")["Quantity"].sum()

np.int64(80974)

In [202]:
data.query("Year == 2011")["Quantity"].sum()

np.int64(64009)

In [203]:
data["Model"].unique()

array(['Volkswagen Passat', 'Toyota Rav4', 'Toyota Avensis',
       'Volkswagen Golf', 'Toyota Corolla', 'Peugeot 307',
       'Skoda Octavia', 'Toyota Yaris', 'Ford Focus', 'Volvo V50',
       'Peugeot 207', 'Audi A4', 'Volkswagen Touran', 'Ford S-Max',
       'Opel Astra', 'Volkswagen Polo', 'Audi A3', 'BMW 3-serie',
       'Opel Vectra', 'Honda CR-V', 'Volvo V70', 'Saab 9-3',
       'Toyota Auris', 'Ford Mondeo', 'Mitsubishi Outlander',
       'Nissan Qashqai', 'Toyota Prius', 'Nissan X-Trail', 'Peugeot 308',
       'Volkswagen Tiguan', 'Skoda Fabia', 'Mazda 6', 'Volvo XC60',
       'Opel Insignia', 'Ford Fiesta', 'Subaru Impreza', 'Hyundai i20',
       'Hyundai i30', 'Toyota Urban Cruiser', 'Peugeot 3008',
       'Suzuki SX4', 'Mitsubishi ASX', 'Suzuki Swift', 'BMW X1',
       'Volvo V60', 'Peugeot 508', 'BMW X3', 'Nissan Leaf', 'Audi Q3',
       'Kia Sportage', 'Mazda CX-5', 'Subaru XV', 'BMW 1-serie',
       'Peugeot 208', 'Skoda Superb', 'Toyota RAV4', 'Hyundai ix35',
       'Volvo V40', 'Volkswagen up!', 'Mercedes-Benz B-klasse',
       "Kia cee'd", 'Citroen C4 Aircross', 'Mercedes-Benz C-klasse',
       'Mercedes-Benz A-klasse', 'Ford Kuga', 'Opel Mokka',
       '\xa0Mercedes-Benz A-klasse', 'Tesla Model S', 'Subaru Forester',
       'Mercedes-Benz E-klasse', 'Peugeot 2008', 'Skoda Yeti',
       'Mercedes-Benz GLK', 'Skoda Rapid', 'Mercedes-Benz CLA', 'BMW i3',
       'Renault Zoe', 'Suzuki Vitara', 'BMW X5', 'BMW 2-serie',
       'Mazda CX-3', 'Volvo XC90', 'Mercedes-Benz GLC', 'Hyundai Tucson',
       'Audi A6', 'Kia Soul', 'Toyota C-HR', 'Tesla Model X', 'Kia Niro',
       'Volvo V90'], dtype=object)

In [204]:
data["Model"].nunique()

90

In [205]:
data["Make"].nunique()

23

In [206]:
data["Make"].unique()

array(['Volkswagen ', 'Toyota ', 'Peugeot ', 'Skoda ', 'Ford ', 'Volvo ',
       'Audi ', 'Opel ', 'BMW ', 'Honda ', 'Saab ', 'Mitsubishi ',
       'Nissan ', 'Mazda ', 'Subaru ', 'Hyundai ', 'Suzuki ', 'Kia ',
       'Mercedes-Benz ', 'Citroen ', '\xa0Mercedes-Benz ', 'Tesla ',
       'Renault '], dtype=object)

In [209]:
data["Make"].isin(["Toyota Avensis", "Audi A3", "Volvo V70"])

0       False
1       False
2       False
3       False
4       False
        ...
2689    False
2690    False
2691    False
2692    False
2693    False
Name: Make, Length: 2694, dtype: bool

In [210]:
data[data["Make"].isin(["Toyota Avensis", "Audi A3", "Volvo V70"])]

Empty DataFrame
Columns: [Year, Month, Make, Model, Quantity, Pct]
Index: []

In [211]:
data_toyota = data[data["Make"] == 'Toyota ']

In [215]:
data_toyota.sort_values(by = "Quantity", ascending= False).head(5)

      Year  Month     Make           Model  Quantity  Pct
1     2007      1  Toyota      Toyota Rav4       819  6.5
2     2007      1  Toyota   Toyota Avensis       787  6.2
2574  2016      8  Toyota      Toyota Rav4       735  5.6
4     2007      1  Toyota   Toyota Corolla       691  5.4
1689  2013     10  Toyota     Toyota Auris       679  5.3

In [216]:
data = pd.read_csv('/Users/fesavaskurt/Python&ML/Kodlarım/Python/ITU/Veri_Analizi_ve_Keşifci_veri_Analizi/pandas_norway_carsales/norway_new_car_sales_by_model.csv', encoding="latin-1", index_col=["Year", "Month", "Make"])

In [217]:
data.head()

                                    Model  Quantity   Pct
Year Month Make
2007 1     Volkswagen   Volkswagen Passat      1267  10.0
           Toyota             Toyota Rav4       819   6.5
           Toyota          Toyota Avensis       787   6.2
           Volkswagen     Volkswagen Golf       720   5.7
           Toyota          Toyota Corolla       691   5.4

In [218]:
data.loc[2010,5]

                            Model  Quantity  Pct
Make
Volkswagen        Volkswagen Golf       559  5.6
Volvo                   Volvo V70       395  4.0
Nissan             Nissan Qashqai       381  3.9
Volkswagen      Volkswagen Passat       334  3.4
Ford                  Ford Mondeo       290  2.9
Toyota             Toyota Avensis       289  2.9
Volkswagen        Volkswagen Polo       279  2.8
Mitsubishi   Mitsubishi Outlander       236  2.4
Audi                      Audi A4       213  2.2
Toyota               Toyota Auris       212  2.1
Ford                  Ford Fiesta       200  2.0
Peugeot              Peugeot 3008       199  2.0
Ford                   Ford Focus       199  2.0
Volkswagen      Volkswagen Tiguan       187  1.9
Skoda               Skoda Octavia       178  1.8
Audi                      Audi A3       175  1.8
Toyota               Toyota Prius       173  1.7
Opel                   Opel Astra       164  1.7
Volvo                   Volvo V50       162  1.6
Toyota       Toyota Urban Cruiser       134  1.4

In [219]:
data = pd.read_csv('/Users/fesavaskurt/Python&ML/Kodlarım/Python/ITU/Veri_Analizi_ve_Keşifci_veri_Analizi/pandas_norway_carsales/norway_new_car_sales_by_model.csv', encoding="latin-1")

In [222]:
data.set_index("Year").head()

      Month         Make              Model  Quantity   Pct
Year
2007      1  Volkswagen   Volkswagen Passat      1267  10.0
2007      1      Toyota         Toyota Rav4       819   6.5
2007      1      Toyota      Toyota Avensis       787   6.2
2007      1  Volkswagen     Volkswagen Golf       720   5.7
2007      1      Toyota      Toyota Corolla       691   5.4

In [223]:
make_total = data.pivot_table(values = "Quantity", index = ["Make", "Model"], aggfunc = "sum")

In [224]:
make_total

                                         Quantity
Make            Model
Audi            Audi A3                     12889
                Audi A4                     15453
                Audi A6                       131
                Audi Q3                       218
BMW             BMW 1-serie                   608
...                                           ...
Volvo           Volvo V70                   32790
                Volvo V90                     202
                Volvo XC60                  11279
                Volvo XC90                   1477
 Mercedes-Benz   Mercedes-Benz A-klasse       184

[90 rows x 1 columns]

#### Remove Space char in the make column

In [225]:
" Toyota ".strip()

'Toyota'

In [227]:
data = data["Make"].str.upper()

### Function Application and Mapping

In [229]:
frame = pd.DataFrame(np.random.randint(0,10,(4, 3)), columns=list('bde'),
                         index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [230]:
frame.min()

b    0
d    2
e    0
dtype: int64

In [231]:
frame.max()

b    9
d    9
e    4
dtype: int64

#### Lambda

Tek satırda fonksiyon yazmak için kullanılır. X aldığı girdi daha sonrasında da max ve mini alıp çıkartacak. Apply metodunun içine fonksiyon koyulması gerekir.

In [232]:
f = lambda x: x.max() - x.min()

In [234]:
frame.apply(f)

b    9
d    7
e    4
dtype: int64

In [235]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [236]:
frame.apply(f)

     b  d  e
min  0  2  0
max  9  9  4

#### Apply

Tablonun kolonlarına çalışıyor.

#### Map

Her hücreye uygulatıyor.